<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class EmpleadoSeeder extends Seeder
{
    public function run()
    {
        $telefonos = [
            'Jhimy Richard Soliz Sanchez' => '62707028',
            'Jhonny Alberto Farfan Aban' => '62850153',
            'Angela Lucia Choque Lopez' => '62850154',
            'Sandra Cruz Rejas' => '62890180',
            'Gabriela Suarez Aranibar' => '67000760',
            'Brian Rodolfo Espejo Candia' => '67000761',
            'Ariel Candi Acarapi' => '67401225',
            'Daniel René Rocha Rocha' => '68226895',
            'Yandira Avalos Cierra' => '68226896',
            'Vania Lizette Orellana' => '68581403',
            'Jhonatan Joel Choque Salazar' => '69208404',
            'Pablo Andres Gamboa' => '69263263',
            'Omar Valdez Muñoz' => '69263344',
            'Paola Suarez Colque' => '69265239',
            'Jhovana Turpo Bautista' => '69265252',
            'Cesar Enrique Jerandilla Calle' => '69293166',
            'Marion Dayana Ortiz Alba' => '69293299',
            'Jheyson Carlos Troche Candia' => '69293611',
            'Evelyn Sisy Balcazar Mendoza' => '69729057',
            'Margaret Mamani Callisaya' => '69729059',
            'Cristina Vereda' => '69775486',
            'Juan Pablo Mamani Camacho' => '69803490',
            'Rommel Joel Beltran Flores' => '69803632',
            'Vanesa Lourdes Aleman Segovia' => '70235566',
            'Carlos Alejandro Bravo Chinchilla' => '71092633',
            'Franklin Aviles Dueñas' => '71163760',
            'Nestor Ramirez Blanco' => '71228587',
            'Lizeth Alison Quispe Chirino' => '71228596',
            'Orlandito Arnez Butron' => '71346100',
            'Edwin Reynaldo Suarez Alcázar' => '71511155',
            'Germin Araceli Chavez Murgia' => '71556421',
            'Vladimir Uluri Mamani' => '71556422',
            'Rocio Morelia Daza Moya' => '71561713',
            'Roxana Antequera Hidalgo' => '71561714',
            'Jaqueline Nirvana Rocha Campero' => '71730002',
            'Velka Micaela Vlahovic Fortun' => '71743513',
            'Edson Pablo Ortiz Sandoval' => '72003319',
            'Jenny Chuquimia Loma' => '72005456',
            'Ismael Hugo Gutierrez Salinas' => '72006162',
            'Ugur Ozmen' => '72006181',
            'Bryan Ramiro Lopez Soria' => '72007456',
            'Juan Orlando Sonco Apaza' => '72007459',
            'Claudia Gisela Guillen de la Torre' => '72042991',
            'Oswaldo Valerio Quisbert Mamani' => '72042997',
            'Milenka Estela Catari Huallpa' => '72043150',
            'Zarely Justiniano Salazar' => '72151808',
            'Jhonny Rocha' => '72228868',
            'Patricia Martinez Salazar' => '72879119',
            'David Espinal Huanaco' => '75227044',
            'Jhoanna Rubithza Aruquipa Ticona' => '76746400',
            'Elizabeth Alejandra Burgos Alba' => '76754567',
            'Ingrid Karen Olivera Atahuichi' => '76754727',
        ];

        $empleados = [
            [
                'ci' => '5994807',
                'nombres' => 'Angela Lucia',
                'apellidos' => 'Choque Lopez',
                'fecha_nacimiento' => '1990-04-26',
                'direccion' => 'Zona Villa Victoria Calle Pacajes Nro. 288',
                'genero' => 'mujer',
                'nacionalidad' => 'Boliviana',
                'telefono_personal' => '70104808',
                'fecha_ingreso' => '2025-02-10',
                'cargo' => 'Analista de licitaciones',
                'sucursal' => 'La Paz',
                'empresa' => 'Novanexa',
                'activo' => true,
                'estado_contrato' => 'Otro'
            ],
            [
                'ci' => '7959901',
                'nombres' => 'Ariel',
                'apellidos' => 'Candi Acarapi',
                'fecha_nacimiento' => '1988-09-21',
                'direccion' => 'Calle los Tajibos S/N V. Moscu',
                'genero' => 'hombre',
                'nacionalidad' => 'Boliviana',
                'telefono_personal' => '71784636',
                'fecha_ingreso' => '2021-12-01',
                'cargo' => 'Auxiliar Técnico',
                'sucursal' => 'Cochabamba',
                'empresa' => 'Requilab',
                'activo' => true,
                'estado_contrato' => 'Otro'
            ],
            [
                'ci' => '7047747',
                'nombres' => 'Brian Rodolfo',
                'apellidos' => 'Espejo Candia',
                'fecha_nacimiento' => '1991-06-18',
                'direccion' => 'Av. Cívica Nro. 777 Zona Villa Tejada Rectangular',
                'genero' => 'hombre',
                'nacionalidad' => 'Boliviana',
                'telefono_personal' => '70634952',
                'fecha_ingreso' => '2022-05-01',
                'cargo' => 'Mensajería',
                'sucursal' => 'La Paz',
                'empresa' => 'Novanexa',
                'activo' => true,
                'estado_contrato' => 'Otro'
            ],
            [
                'ci' => '5958993',
                'nombres' => 'Bryan Ramiro',
                'apellidos' => 'Lopez Soria',
                'fecha_nacimiento' => '1985-12-22',
                'direccion' => 'Zona Villa Copacabana',
                'genero' => 'hombre',
                'nacionalidad' => 'Boliviana',
                'telefono_personal' => '69822287',
                'fecha_ingreso' => '2023-08-24',
                'cargo' => 'Contador',
                'sucursal' => 'La Paz',
                'empresa' => 'Requilab',
                'activo' => true,
                'estado_contrato' => 'Otro'
            ],
            [
                'ci' => '8178335',
                'nombres' => 'Carlos Alejandro',
                'apellidos' => 'Bravo Chinchilla',
                'fecha_nacimiento' => '2000-03-05',
                'direccion' => 'B/Grigota C/22 Satelite Norte',
                'genero' => 'hombre',
                'nacionalidad' => 'Boliviana',
                'telefono_personal' => '65289830',
                'fecha_ingreso' => '2022-11-15',
                'cargo' => 'Auxiliar de Almacén',
                'sucursal' => 'Santa Cruz',
                'empresa' => 'Novanexa',
                'activo' => true,
                'estado_contrato' => 'Otro'
            ],
            [
                'ci' => '8441669',
                'nombres' => 'Cesar Enrique',
                'apellidos' => 'Jerandilla Calle',
                'fecha_nacimiento' => '1994-06-19',
                'direccion' => 'Calle 2 Nro. 4 Zona Santa Rosa, El Alto',
                'genero' => 'hombre',
                'nacionalidad' => 'Boliviana',
                'telefono_personal' => '73537185',
                'fecha_ingreso' => '2024-09-01',
                'cargo' => 'Auxiliar Contable',
                'sucursal' => 'La Paz',
                'empresa' => 'Novanexa',
                'activo' => true,
                'estado_contrato' => 'Otro'
            ],
            [
                'ci' => '4777512',
                'nombres' => 'Claudia Gisela',
                'apellidos' => 'Guillen de la Torre',
                'fecha_nacimiento' => '1977-01-11',
                'direccion' => 'Calle 14 Esquina Santiago Fajardo Nro. 50, Zona Achumani',
                'genero' => 'mujer',
                'nacionalidad' => 'Boliviana',
                'telefono_personal' => '69827848',
                'fecha_ingreso' => '2024-10-01',
                'cargo' => 'Asesor Bioquímico Comercial',
                'sucursal' => 'La Paz',
                'empresa' => 'Ireilab',
                'activo' => true,
                'estado_contrato' => 'Otro'
            ],
            [
                'ci' => '5918674',
                'nombres' => 'Cristina',
                'apellidos' => 'Vereda',
                'fecha_nacimiento' => '1985-04-06',
                'direccion' => 'Zona Sud-Calle Miguel Ferrufino Nro. 265',
                'genero' => 'mujer',
                'nacionalidad' => 'Boliviana',
                'telefono_personal' => '75911967',
                'fecha_ingreso' => '2019-12-01',
                'cargo' => 'Ejecutivo de Ventas',
                'sucursal' => 'Cochabamba',
                'empresa' => 'Requilab',
                'activo' => true,
                'estado_contrato' => 'Otro'
            ],
            [
                'ci' => '9434456',
                'nombres' => 'Daniel René',
                'apellidos' => 'Rocha Rocha',
                'fecha_nacimiento' => '1996-05-21',
                'direccion' => 'Av. Petrolera Km4. Barrio Ferroviario',
                'genero' => 'hombre',
                'nacionalidad' => 'Boliviana',
                'telefono_personal' => '72299801',
                'fecha_ingreso' => '2023-05-04',
                'cargo' => 'Auxiliar Técnico',
                'sucursal' => 'Cochabamba',
                'empresa' => 'Novanexa',
                'activo' => true,
                'estado_contrato' => 'Otro'
            ],
            [
                'ci' => '6990618',
                'nombres' => 'David',
                'apellidos' => 'Espinal Huanaco',
                'fecha_nacimiento' => '1991-03-17',
                'direccion' => 'Avenida Primavera Nro.1480, 21 de semtiembre, El Alto',
                'genero' => 'hombre',
                'nacionalidad' => 'Boliviana',
                'telefono_personal' => '75227044',
                'fecha_ingreso' => '2025-04-07',
                'cargo' => 'Auxiliar Contable',
                'sucursal' => 'La Paz',
                'empresa' => 'Ireilab',
                'activo' => true,
                'estado_contrato' => 'Otro'
            ],
            [
                'ci' => '471844',
                'nombres' => 'Edwin Reynaldo',
                'apellidos' => 'Suarez Alcázar',
                'fecha_nacimiento' => '1955-07-08',
                'direccion' => 'Calle Canonigo N°801, Zona San Pedro',
                'genero' => 'hombre',
                'nacionalidad' => 'Boliviana',
                'telefono_personal' => null,
                'fecha_ingreso' => '2022-05-01',
                'cargo' => 'Administrador',
                'sucursal' => 'La Paz',
                'empresa' => 'Novanexa',
                'activo' => true,
                'estado_contrato' => 'Otro'
            ],
            [
                'ci' => '12856622',
                'nombres' => 'Elizabeth Alejandra',
                'apellidos' => 'Burgos Alba',
                'fecha_nacimiento' => '1997-10-11',
                'direccion' => 'B/Nueva Primavera Zona Norte',
                'genero' => 'mujer',
                'nacionalidad' => 'Boliviana',
                'telefono_personal' => '76627149',
                'fecha_ingreso' => '2023-07-04',
                'cargo' => 'Asesor Bioquímico Comercial',
                'sucursal' => 'Santa Cruz',
                'empresa' => 'Novanexa',
                'activo' => true,
                'estado_contrato' => 'Otro'
            ],
            [
                'ci' => '8422084',
                'nombres' => 'Evelyn Sisy',
                'apellidos' => 'Balcazar Mendoza',
                'fecha_nacimiento' => '1990-11-22',
                'direccion' => 'Calle Vicente Ochoa Nro. 763 Zona Gran Poder',
                'genero' => 'mujer',
                'nacionalidad' => 'Boliviana',
                'telefono_personal' => '75264691',
                'fecha_ingreso' => '2024-08-01',
                'cargo' => 'Asistente Administrativo',
                'sucursal' => 'La Paz',
                'empresa' => 'Ireilab',
                'activo' => true,
                'estado_contrato' => 'Otro'
            ],
            [
                'ci' => '5036675',
                'nombres' => 'Jhonny Alberto',
                'apellidos' => 'Farfan Aban',
                'fecha_nacimiento' => '1985-10-20',
                'direccion' => 'Urbanización Moto Mendez',
                'genero' => 'hombre',
                'nacionalidad' => 'Boliviana',
                'telefono_personal' => '78251411',
                'fecha_ingreso' => '2023-07-26',
                'cargo' => 'Encargado Regional',
                'sucursal' => 'Tarija',
                'empresa' => 'Novanexa',
                'activo' => true,
                'estado_contrato' => 'Otro'
            ],
            [
                'ci' => '12740098',
                'nombres' => 'Franklin',
                'apellidos' => 'Aviles Dueñas',
                'fecha_nacimiento' => '1995-05-31',
                'direccion' => 'Avenida Jaime Mendoza Nro.2650',
                'genero' => 'hombre',
                'nacionalidad' => 'Boliviana',
                'telefono_personal' => '75442689',
                'fecha_ingreso' => '2025-05-02',
                'cargo' => 'Auxiliar de Almacén',
                'sucursal' => 'Sucre',
                'empresa' => 'Novanexa',
                'activo' => true,
                'estado_contrato' => 'Otro'
            ],
            [
                'ci' => '6139368',
                'nombres' => 'Gabriela',
                'apellidos' => 'Suarez Aranibar',
                'fecha_nacimiento' => '1984-09-18',
                'direccion' => 'No indica',
                'genero' => 'mujer',
                'nacionalidad' => 'Boliviana',
                'telefono_personal' => null,
                'fecha_ingreso' => '2024-08-01',
                'cargo' => 'Gerente General',
                'sucursal' => 'La Paz',
                'empresa' => 'Requilab',
                'activo' => true,
                'estado_contrato' => 'Otro'
            ],
            [
                'ci' => '9875657',
                'nombres' => 'Ingrid Karen',
                'apellidos' => 'Olivera Atahuichi',
                'fecha_nacimiento' => '1992-11-30',
                'direccion' => 'Av. Santos Dumont entre 5to anillo y 6to Anillo, Calle #5',
                'genero' => 'mujer',
                'nacionalidad' => 'Boliviana',
                'telefono_personal' => '63260514',
                'fecha_ingreso' => '2022-06-01',
                'cargo' => 'Encargado Regional',
                'sucursal' => 'Santa Cruz',
                'empresa' => 'Novanexa',
                'activo' => true,
                'estado_contrato' => 'Otro'
            ],
            [
                'ci' => '4886851',
                'nombres' => 'Ismael Hugo',
                'apellidos' => 'Gutierrez Salinas',
                'fecha_nacimiento' => '1980-08-17',
                'direccion' => 'Zona Villa Salome Sector Grafico Calle 1 Nro. 1405',
                'genero' => 'hombre',
                'nacionalidad' => 'Boliviana',
                'telefono_personal' => '72052256',
                'fecha_ingreso' => '2025-03-01',
                'cargo' => 'Encargado Nacional de Almacén',
                'sucursal' => 'La Paz',
                'empresa' => 'Novanexa',
                'activo' => true,
                'estado_contrato' => 'Otro'
            ],
            [
                'ci' => '4402303',
                'nombres' => 'Jaqueline Nirvana',
                'apellidos' => 'Rocha Campero',
                'fecha_nacimiento' => '1974-05-12',
                'direccion' => 'Calle Araona S/N Zona Condebamba',
                'genero' => 'mujer',
                'nacionalidad' => 'Boliviana',
                'telefono_personal' => '75918265',
                'fecha_ingreso' => '2024-03-01',
                'cargo' => 'Ejecutivo de Ventas',
                'sucursal' => 'Cochabamba',
                'empresa' => 'Novanexa',
                'activo' => true,
                'estado_contrato' => 'Otro'
            ],
            [
                'ci' => '3391161',
                'nombres' => 'Jenny',
                'apellidos' => 'Chuquimia Loma',
                'fecha_nacimiento' => '1968-06-12',
                'direccion' => 'Av. Costanera N°505 Zona Alto Obrajes',
                'genero' => 'mujer',
                'nacionalidad' => 'Boliviana',
                'telefono_personal' => '69909942',
                'fecha_ingreso' => '2025-01-24',
                'cargo' => 'Gerente Administrativo Financiero',
                'sucursal' => 'La Paz',
                'empresa' => 'Ireilab',
                'activo' => true,
                'estado_contrato' => 'Otro'
            ],
            [
                'ci' => '8278245',
                'nombres' => 'Jheyson Carlos',
                'apellidos' => 'Troche Candia',
                'fecha_nacimiento' => '1988-10-18',
                'direccion' => 'Av. Juan José Torrez Zona Alto Llojeta Nro. 6',
                'genero' => 'hombre',
                'nacionalidad' => 'Boliviana',
                'telefono_personal' => '61279487',
                'fecha_ingreso' => '2024-08-01',
                'cargo' => 'Encargado de Almacén',
                'sucursal' => 'La Paz',
                'empresa' => 'Ireilab',
                'activo' => true,
                'estado_contrato' => 'Otro'
            ],
            [
                'ci' => '6442969',
                'nombres' => 'Jhimy Richard',
                'apellidos' => 'Soliz Sanchez',
                'fecha_nacimiento' => '1985-10-24',
                'direccion' => 'Zona el Castillo Z/N Sacaba',
                'genero' => 'hombre',
                'nacionalidad' => 'Boliviana',
                'telefono_personal' => '65707803',
                'fecha_ingreso' => '2024-10-01',
                'cargo' => 'Auxiliar de Almacén',
                'sucursal' => 'Cochabamba',
                'empresa' => 'Ireilab',
                'activo' => true,
                'estado_contrato' => 'Otro'
            ],
            [
                'ci' => '6196876',
                'nombres' => 'Jhoanna Rubithza',
                'apellidos' => 'Aruquipa Ticona',
                'fecha_nacimiento' => '1985-04-16',
                'direccion' => 'Av. Mario Mercado Nro. 310, Zona Llojeta',
                'genero' => 'mujer',
                'nacionalidad' => 'Boliviana',
                'telefono_personal' => '60638131',
                'fecha_ingreso' => '2024-10-01',
                'cargo' => 'Encargado de Licitaciones',
                'sucursal' => 'La Paz',
                'empresa' => 'Ireilab',
                'activo' => true,
                'estado_contrato' => 'Otro'
            ],
            [
                'ci' => '9190199',
                'nombres' => 'Jhonatan Joel',
                'apellidos' => 'Choque Salazar',
                'fecha_nacimiento' => '2002-04-30',
                'direccion' => 'Rest. En Clara Chuchio - Prov. Warnes',
                'genero' => 'hombre',
                'nacionalidad' => 'Boliviana',
                'telefono_personal' => '68306545',
                'fecha_ingreso' => '2024-01-08',
                'cargo' => 'Asistente Administrativo',
                'sucursal' => 'Santa Cruz',
                'empresa' => 'Requilab',
                'activo' => true,
                'estado_contrato' => 'Otro'
            ],
            [
                'ci' => '5173877',
                'nombres' => 'Juan Orlando',
                'apellidos' => 'Sonco Apaza',
                'fecha_nacimiento' => '1989-06-28',
                'direccion' => 'Av. Panamericana S/N-B, Don Bosco',
                'genero' => 'hombre',
                'nacionalidad' => 'Boliviana',
                'telefono_personal' => '77486331',
                'fecha_ingreso' => '2023-02-01',
                'cargo' => 'Asesor Bioquímico Comercial',
                'sucursal' => 'Cochabamba',
                'empresa' => 'Novanexa',
                'activo' => true,
                'estado_contrato' => 'Otro'
            ],
            [
                'ci' => '7164908',
                'nombres' => 'Juan Pablo',
                'apellidos' => 'Mamani Camacho',
                'fecha_nacimiento' => '1993-03-29',
                'direccion' => 'Niño de Tiquipaya',
                'genero' => 'hombre',
                'nacionalidad' => 'Boliviana',
                'telefono_personal' => '72992646',
                'fecha_ingreso' => '2024-11-01',
                'cargo' => 'Auxiliar Técnico',
                'sucursal' => 'Cochabamba',
                'empresa' => 'Ireilab',
                'activo' => true,
                'estado_contrato' => 'Otro'
            ],
            [
                'ci' => '11067202',
                'nombres' => 'Margaret',
                'apellidos' => 'Mamani Callisaya',
                'fecha_nacimiento' => '2002-01-12',
                'direccion' => 'Zona Armando Escobar Uria C/9',
                'genero' => 'mujer',
                'nacionalidad' => 'Boliviana',
                'telefono_personal' => '74902706',
                'fecha_ingreso' => '2024-10-10',
                'cargo' => 'Auxiliar Administrativo y Comercial',
                'sucursal' => 'La Paz',
                'empresa' => 'Novanexa',
                'activo' => true,
                'estado_contrato' => 'Otro'
            ],
            [
                'ci' => '9083636',
                'nombres' => 'Marion Dayana',
                'apellidos' => 'Ortiz Alba',
                'fecha_nacimiento' => '1997-09-24',
                'direccion' => 'Av. Franco Valle C. 4 y 5 Nro. 87 Zona 12 de octubre El Alto',
                'genero' => 'mujer',
                'nacionalidad' => 'Boliviana',
                'telefono_personal' => '75878843',
                'fecha_ingreso' => '2024-10-04',
                'cargo' => 'Regente Farmacéutico',
                'sucursal' => 'La Paz',
                'empresa' => 'Ireilab',
                'activo' => true,
                'estado_contrato' => 'Otro'
            ],
            [
                'ci' => '6071176',
                'nombres' => 'Milenka Estela',
                'apellidos' => 'Catari Huallpa',
                'fecha_nacimiento' => '1991-03-23',
                'direccion' => 'Calle Ontirraymi Nro 60 Zona Cotahuma',
                'genero' => 'mujer',
                'nacionalidad' => 'Boliviana',
                'telefono_personal' => '69714711',
                'fecha_ingreso' => '2024-01-26',
                'cargo' => 'Regente Farmacéutico',
                'sucursal' => 'La Paz',
                'empresa' => 'Novanexa',
                'activo' => true,
                'estado_contrato' => 'Otro'
            ],
            [
                'ci' => '9249503',
                'nombres' => 'Nestor',
                'apellidos' => 'Ramirez Blanco',
                'fecha_nacimiento' => '1994-10-19',
                'direccion' => 'Barrio C.J. Bautista Nro. 1054 Zona San Pedro Domingo Murillo',
                'genero' => 'hombre',
                'nacionalidad' => 'Boliviana',
                'telefono_personal' => '77705169',
                'fecha_ingreso' => '2021-06-01',
                'cargo' => 'Auxiliar Técnico',
                'sucursal' => 'La Paz',
                'empresa' => 'Requilab',
                'activo' => true,
                'estado_contrato' => 'Otro'
            ],
            [
                'ci' => '6833216',
                'nombres' => 'Omar',
                'apellidos' => 'Valdez Muñoz',
                'fecha_nacimiento' => '1987-12-20',
                'direccion' => 'Calle 25 de julio N°13060 Zona Las Delicias',
                'genero' => 'hombre',
                'nacionalidad' => 'Boliviana',
                'telefono_personal' => null,
                'fecha_ingreso' => '2025-02-03',
                'cargo' => 'Encargado de Tecnologías de la Información',
                'sucursal' => 'La Paz',
                'empresa' => 'Ireilab',
                'activo' => true,
                'estado_contrato' => 'Otro'
            ],
            [
                'ci' => '8249233',
                'nombres' => 'Orlandito',
                'apellidos' => 'Arnez Butron',
                'fecha_nacimiento' => '1999-08-11',
                'direccion' => 'Av. V. de Lujan 9°A B/Bibosi S/N',
                'genero' => 'hombre',
                'nacionalidad' => 'Boliviana',
                'telefono_personal' => '75683211',
                'fecha_ingreso' => '2023-09-28',
                'cargo' => 'Auxiliar de Almacén',
                'sucursal' => 'Santa Cruz',
                'empresa' => 'Requilab',
                'activo' => true,
                'estado_contrato' => 'Otro'
            ],
            [
                'ci' => '6729631',
                'nombres' => 'Oswaldo Valerio',
                'apellidos' => 'Quisbert Mamani',
                'fecha_nacimiento' => '1986-06-14',
                'direccion' => 'Zona Munaypata, Avenida Florida Nro. 398',
                'genero' => 'hombre',
                'nacionalidad' => 'Boliviana',
                'telefono_personal' => '77741861',
                'fecha_ingreso' => '2024-10-01',
                'cargo' => 'Asesor Bioquímico Comercial',
                'sucursal' => 'La Paz',
                'empresa' => 'Novanexa',
                'activo' => false,
                'estado_contrato' => 'Otro'
            ],
            [
                'ci' => '11601675',
                'nombres' => 'Pablo Andres',
                'apellidos' => 'Gamboa',
                'fecha_nacimiento' => '1998-01-19',
                'direccion' => 'Calle Antonio Gallardo Nro.1025',
                'genero' => 'hombre',
                'nacionalidad' => 'Boliviana',
                'telefono_personal' => '67790294',
                'fecha_ingreso' => '2024-08-01',
                'cargo' => 'Auxiliar de Almacén',
                'sucursal' => 'La Paz',
                'empresa' => 'Ireilab',
                'activo' => true,
                'estado_contrato' => 'Otro'
            ],
            [
                'ci' => '4101450',
                'nombres' => 'Patricia',
                'apellidos' => 'Martinez Salazar',
                'fecha_nacimiento' => '1981-04-25',
                'direccion' => 'Calle La Paz Nro. 433',
                'genero' => 'mujer',
                'nacionalidad' => 'Boliviana',
                'telefono_personal' => '67611082',
                'fecha_ingreso' => '2022-05-01',
                'cargo' => 'Ejecutivo de Ventas',
                'sucursal' => 'Sucre',
                'empresa' => 'Novanexa',
                'activo' => true,
                'estado_contrato' => 'Otro'
            ],
            [
                'ci' => '4764878',
                'nombres' => 'Roxana',
                'apellidos' => 'Antequera Hidalgo',
                'direccion' => 'Calle Final Beni Zona Norte La Paz',
                'genero' => 'mujer',
                'nacionalidad' => 'Boliviana',
                'telefono_personal' => null,
                'fecha_ingreso' => '2025-02-17',
                'cargo' => 'Encargado de Contabilidad',
                'sucursal' => 'La Paz',
                'empresa' => 'Ireilab',
                'activo' => false,
                'estado_contrato' => 'Otro'
            ],
            [
                'ci' => '7536902',
                'nombres' => 'Sandra',
                'apellidos' => 'Cruz Rejas',
                'fecha_nacimiento' => '1990-09-01',
                'direccion' => 'Calle 25 de Mayo Nro. 65, Zona Cementerio',
                'genero' => 'mujer',
                'nacionalidad' => 'Boliviana',
                'telefono_personal' => '77132707',
                'fecha_ingreso' => '2024-01-02',
                'cargo' => 'Asesor Bioquímico Comercial',
                'sucursal' => 'Sucre',
                'empresa' => 'Novanexa',
                'activo' => true,
                'estado_contrato' => 'Otro'
            ],
            [
                'ci' => 'U24573798',
                'nombres' => 'Ugur',
                'apellidos' => 'Ozmen',
                'fecha_nacimiento' => '1994-10-30',
                'direccion' => 'Calle Francisco de Miranda Nro. 2198 Zona Miraflores',
                'genero' => 'hombre',
                'nacionalidad' => 'Turca',
                'telefono_personal' => null,
                'fecha_ingreso' => '2024-09-01',
                'cargo' => 'Gerente Ejecutivo',
                'sucursal' => 'La Paz',
                'empresa' => 'Ireilab',
                'activo' => true,
                'estado_contrato' => 'Otro'
            ],
            [
                'ci' => '4153229',
                'nombres' => 'Vanesa Lourdes',
                'apellidos' => 'Aleman Segovia',
                'direccion' => 'C/Pando, B/ Avaroa',
                'genero' => 'mujer',
                'nacionalidad' => 'Boliviana',
                'telefono_personal' => '70235566',
                'fecha_ingreso' => '2025-04-04',
                'cargo' => 'Auxiliar de Almacén',
                'sucursal' => 'Tarija',
                'empresa' => 'Novanexa',
                'activo' => true,
                'estado_contrato' => 'Otro'
            ],
            [
                'ci' => '7940279',
                'nombres' => 'Vania Lizette',
                'apellidos' => 'Orellana',
                'fecha_nacimiento' => '1992-02-08',
                'direccion' => 'Zona Sud Barrio Minero Alalay Nro. 177',
                'genero' => 'mujer',
                'nacionalidad' => 'Boliviana',
                'telefono_personal' => '63901514',
                'fecha_ingreso' => '2024-10-01',
                'cargo' => 'Asistente Administrativo',
                'sucursal' => 'Cochabamba',
                'empresa' => 'Ireilab',
                'activo' => true,
                'estado_contrato' => 'Otro'
            ],
            [
                'ci' => '5190764',
                'nombres' => 'Velka Micaela',
                'apellidos' => 'Vlahovic Fortun',
                'fecha_nacimiento' => '1980-03-23',
                'direccion' => 'Urb. Lab Zona Esmeralda Norte S/N',
                'genero' => 'mujer',
                'nacionalidad' => 'Boliviana',
                'telefono_personal' => '70761904',
                'fecha_ingreso' => '2021-03-01',
                'cargo' => 'Encargado Regional',
                'sucursal' => 'Cochabamba',
                'empresa' => 'Requilab',
                'activo' => true,
                'estado_contrato' => 'Otro'
            ],
            [
                'ci' => '6989713',
                'nombres' => 'Vladimir',
                'apellidos' => 'Uluri Mamani',
                'fecha_nacimiento' => '1991-08-25',
                'direccion' => 'Av. Inca Rosa Nro.4094 Zona Nueva Jerusalén',
                'genero' => 'hombre',
                'nacionalidad' => 'Boliviana',
                'telefono_personal' => '71264679',
                'fecha_ingreso' => '2024-08-01',
                'cargo' => 'Auxiliar Técnico',
                'sucursal' => 'La Paz',
                'empresa' => 'Ireilab',
                'activo' => true,
                'estado_contrato' => 'Otro'
            ],
            [
                'ci' => '6380855',
                'nombres' => 'Yandira',
                'apellidos' => 'Avalos Cierra',
                'fecha_nacimiento' => '1987-01-02',
                'direccion' => 'Zona Sur Av. Santa Barbara Calle Rio Caine Nro. 100',
                'genero' => 'mujer',
                'nacionalidad' => 'Boliviana',
                'telefono_personal' => '68226896',
                'fecha_ingreso' => '2024-01-08',
                'cargo' => 'Asesor Bioquímico Aplicacionista',
                'sucursal' => 'Cochabamba',
                'empresa' => 'Novanexa',
                'activo' => true,
                'estado_contrato' => 'Otro'
            ],
            [
                'ci' => '4313403',
                'nombres' => 'Edson Pablo',
                'apellidos' => 'Ortiz Sandoval',
                'genero' => 'hombre',
                'nacionalidad' => 'Boliviana',
                'fecha_ingreso' => '2025-03-05',
                'cargo' => 'Encargado de Logistica e Importaciones',
                'sucursal' => 'La Paz',
                'empresa' => 'Novanexa',
                'activo' => true,
                'estado_contrato' => 'Otro'
            ],
            [
                'ci' => '6983933',
                'nombres' => 'Germin Araceli',
                'apellidos' => 'Chavez Murgia',
                'genero' => 'mujer',
                'nacionalidad' => 'Boliviana',
                'fecha_ingreso' => '2025-03-10',
                'cargo' => 'Auxiliar Contable',
                'sucursal' => 'La Paz',
                'empresa' => 'Novanexa',
                'activo' => true,
                'estado_contrato' => 'Otro'
            ],
            [
                'ci' => '10072126',
                'nombres' => 'Jhovana',
                'apellidos' => 'Turpo Bautista',
                'direccion' => 'Calle 24 de amyo Zona Bautista',
                'genero' => 'mujer',
                'nacionalidad' => 'Boliviana',
                'telefono_personal' => '70191649',
                'fecha_ingreso' => '2025-02-18',
                'cargo' => 'Auxiliar Técnico',
                'sucursal' => 'La Paz',
                'empresa' => 'Ireilab',
                'activo' => true,
                'estado_contrato' => 'Otro'
            ],
            [
                'ci' => '5271275',
                'nombres' => 'Jhonny',
                'apellidos' => 'Rocha',
                'genero' => 'hombre',
                'nacionalidad' => 'Boliviana',
                'fecha_ingreso' => '2025-03-17',
                'cargo' => 'Encargado de Almacén',
                'sucursal' => 'Cochabamba',
                'empresa' => 'Novanexa',
                'activo' => true,
                'estado_contrato' => 'Otro'
            ],
            [
                'ci' => '12573520',
                'nombres' => 'Lizeth Alison',
                'apellidos' => 'Quispe Chirino',
                'direccion' => 'Zona San Luis Tasa Av. Héroes del Pacífico Nro. 51',
                'genero' => 'mujer',
                'nacionalidad' => 'Boliviana',
                'telefono_personal' => '60546925',
                'fecha_ingreso' => '2025-02-03',
                'cargo' => 'Auxiliar Contable',
                'sucursal' => 'La Paz',
                'empresa' => 'Novanexa',
                'activo' => true,
                'estado_contrato' => 'Otro'
            ],
            [
                'ci' => '9351737',
                'nombres' => 'Paola',
                'apellidos' => 'Suarez Colque',
                'genero' => 'mujer',
                'nacionalidad' => 'Boliviana',
                'fecha_ingreso' => '2025-03-24',
                'cargo' => 'Asesor Bioquímico Comercial',
                'sucursal' => 'Cochabamba',
                'empresa' => 'Ireilab',
                'activo' => true,
                'estado_contrato' => 'Otro'
            ],
            [
                'ci' => '6998044',
                'nombres' => 'Rocio Morelia',
                'apellidos' => 'Daza Moya',
                'genero' => 'mujer',
                'nacionalidad' => 'Boliviana',
                'fecha_ingreso' => '2025-03-18',
                'cargo' => 'Asistente de Licitaciones',
                'sucursal' => 'La Paz',
                'empresa' => 'Novanexa',
                'activo' => true,
                'estado_contrato' => 'Otro'
            ],
            [
                'ci' => '4951011',
                'nombres' => 'Rommel Joel',
                'apellidos' => 'Beltran Flores',
                'fecha_nacimiento' => '1975-10-20',
                'genero' => 'hombre',
                'nacionalidad' => 'Boliviana',
                'fecha_ingreso' => '2025-04-14',
                'cargo' => 'Encargado de Recursos Humanos',
                'sucursal' => 'La Paz',
                'empresa' => 'Ireilab',
                'activo' => true,
                'estado_contrato' => 'Otro'
            ],
            [
                'ci' => '12564920',
                'nombres' => 'Zarely',
                'apellidos' => 'Justiniano Salazar',
                'genero' => 'mujer',
                'nacionalidad' => 'Boliviana',
                'fecha_ingreso' => '2025-03-18',
                'cargo' => 'Asesor Bioquímico Comercial',
                'sucursal' => 'Santa Cruz',
                'empresa' => 'Novanexa',
                'activo' => true,
                'estado_contrato' => 'Otro'
            ]
        ];

        foreach ($empleados as $empleado) {
            // Verificar si el empleado ya existe
            if ($empleado['ci'] && DB::table('rh_empleados')->where('ci', $empleado['ci'])->exists()) {
                continue;
            }

            // Generar correo corporativo
            $primerNombre = strtolower(explode(' ', $empleado['nombres'])[0]);
            $primerApellido = strtolower(explode(' ', $empleado['apellidos'])[0]);
            $dominioEmpresa = strtolower($empleado['empresa']) . '.com.bo';
            $correoCorporativo = "$primerNombre.$primerApellido@$dominioEmpresa";

            // Buscar número corporativo
            $nombreCompleto = trim($empleado['nombres'] . ' ' . $empleado['apellidos']);
            $numeroCorporativo = $telefonos[$nombreCompleto] ?? null;

            // Preparar datos para insertar - TODOS los campos de la migración deben estar aquí
            $datosInsertar = [
                'ci' => $empleado['ci'],
                'nombres' => $empleado['nombres'],
                'apellidos' => $empleado['apellidos'],
                'fecha_nacimiento' => $empleado['fecha_nacimiento'] ?? null,
                'direccion' => $empleado['direccion'] ?? null,
                'ubicacion_gps' => null, // O json_encode([]) si necesitas
                'genero' => $empleado['genero'],
                'nacionalidad' => $empleado['nacionalidad'],
                'estado_civil' => null,
                'cantidad_hijos' => null,
                'telefono_personal' => $empleado['telefono_personal'] ?? null,
                'correo_personal' => null,
                'persona_contacto' => null,
                'numero_contacto' => null,
                'persona_parentesco' => null,
                'nua_cua' => null,
                'activo' => $empleado['activo'],
                'foto' => null,
                'fecha_ingreso' => $empleado['fecha_ingreso'],
                'fecha_desvinculacion' => null,
                'estado_contrato' => 'Otro',
                'afp' => null,
                'caja_salud' => null,
                'correo_corporativo' => $correoCorporativo,
                'numero_corporativo' => $numeroCorporativo,
                'cargo' => $empleado['cargo'],
                'sucursal' => $empleado['sucursal'],
                'empresa' => $empleado['empresa'],
                'salario' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ];

            // Insertar el empleado
            DB::table('rh_empleados')->insert($datosInsertar);
        }
    }
}
